name: AI Job Agent (Hourly)

on:
  schedule:
    - cron: '0 * * * *'        # every hour at :00
  workflow_dispatch:            # allow manual runs

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas openpyxl

      - name: Prepare output & seen file
        run: |
          mkdir -p out
          touch seen.csv

      - name: Run agent
        env:
          INPUT_EXCEL: companies.xlsx
          OUTPUT_DIR: out
          SEEN_PATH: seen.csv
        run: python job_agent_multi.py

      - name: Commit report (if new)
        shell: bash
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          ADDED=0
          if compgen -G "out/*.xlsx" > /dev/null; then
            git add out/*.xlsx || true
            ADDED=1
          fi
          if [ -f seen.csv ]; then
            git add seen.csv || true
            ADDED=1
          fi

          if [ "$ADDED" -eq 1 ] && ! git diff --cached --quiet; then
            git commit -m "Report $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No files to commit."
          fi
