name: AI Job Agent (Hourly)

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour at minute 0
  workflow_dispatch:      # lets you trigger it manually from GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas openpyxl

      - name: Prepare output folder
        run: mkdir -p out

      - name: Run agent
        env:
          INPUT_EXCEL: companies.xlsx
          OUTPUT_DIR: out
          SEEN_PATH: seen.csv
        run: python job_agent_multi.py

      - name: Commit report (if new)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add out/*.xlsx seen.csv || true
            git commit -m "Report $(date -u +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes"
          fi
